INSERT INTO page_texto (texto, date_created) VALUES
                                                 ('Hola!', CURRENT_TIMESTAMP),
                                                 ('Talvez sea la primera vez que te veo por acá.', CURRENT_TIMESTAMP),
                                                 ('Lamento informarte que este sitio solo es visible desde un computador.', CURRENT_TIMESTAMP),
                                                 ('Nos vemos allá!', CURRENT_TIMESTAMP),
                                                 ('Cargando mapa…', CURRENT_TIMESTAMP),
                                                 ('Hola!!', CURRENT_TIMESTAMP),
                                                 ('Espero que estés bien', CURRENT_TIMESTAMP),
                                                 ('Te vamos a ayudar a encontrar a tu mascota', CURRENT_TIMESTAMP),
                                                 ('Para eso necesito que busques en la barra de arriba la dirección en donde ocurrió', CURRENT_TIMESTAMP),
                                                 ('Muy bien!!', CURRENT_TIMESTAMP),
                                                 ('ahora presiona el botón inicio que está debajo de mi', CURRENT_TIMESTAMP),
                                                 ('Bien, ya lo estás entendiendo!!', CURRENT_TIMESTAMP),
                                                 ('Ahora indica si la perdiste o si la encontraste y rellena el formulario', CURRENT_TIMESTAMP),
                                                 ('inicio', CURRENT_TIMESTAMP),
                                                 ('> mascota extraviada', CURRENT_TIMESTAMP),
                                                 ('> mascota encontrada', CURRENT_TIMESTAMP),
                                                 ('Perdí una mascota', CURRENT_TIMESTAMP),
                                                 ('Encontré una mascota', CURRENT_TIMESTAMP),
                                                 ('Fecha que la encontré', CURRENT_TIMESTAMP),
                                                 ('Fecha en la que se perdió', CURRENT_TIMESTAMP),
                                                 ('Nombre (opcional)', CURRENT_TIMESTAMP),
                                                 ('Nombre al que responde', CURRENT_TIMESTAMP),
                                                 ('Fotos (max 10, max 5mg)', CURRENT_TIMESTAMP),
                                                 ('subir', CURRENT_TIMESTAMP),
                                                 ('Guardar', CURRENT_TIMESTAMP),
                                                 ('Guardando...', CURRENT_TIMESTAMP),
                                                 ('Se perdió cerca de:', CURRENT_TIMESTAMP),
                                                 ('Se encontró cerca de:', CURRENT_TIMESTAMP),
                                                 ('Publicado por:', CURRENT_TIMESTAMP),
                                                 ('Correo:', CURRENT_TIMESTAMP),
                                                 ('Copiado', CURRENT_TIMESTAMP),
                                                 ('Cerrar', CURRENT_TIMESTAMP),
                                                 ('Mascota encontrada', CURRENT_TIMESTAMP),
                                                 ('Mascota perdida', CURRENT_TIMESTAMP),
                                                 ('Fecha de hallazgo', CURRENT_TIMESTAMP),
                                                 ('Fecha de extravío', CURRENT_TIMESTAMP),
                                                 ('Buscar ciudad, dirección o lugar', CURRENT_TIMESTAMP),
                                                 ('No disponible', CURRENT_TIMESTAMP),
                                                 ('No se pudo buscar la ubicación.', CURRENT_TIMESTAMP),
                                                 ('No se encontraron resultados.', CURRENT_TIMESTAMP),
                                                 ('Falta configurar NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN.', CURRENT_TIMESTAMP),
                                                 ('Debes subir al menos una foto antes de guardar.', CURRENT_TIMESTAMP),
                                                 ('Solo se permiten archivos de imagen.', CURRENT_TIMESTAMP),
                                                 ('Puedes seleccionar hasta 10 fotos.', CURRENT_TIMESTAMP),
                                                 ('No se pudieron subir las fotos.', CURRENT_TIMESTAMP),
                                                 ('Debes seleccionar un lugar donde se perdió su mascota, arriba en el buscador, busque su dirección', CURRENT_TIMESTAMP),
                                                 ('Debe seleccionar un lugar donde encontró la mascota, arriba en el buscador, busque su dirección', CURRENT_TIMESTAMP),
                                                 ('Debes ingresar fecha y nombre para guardar.', CURRENT_TIMESTAMP),
                                                 ('Debes ingresar fecha para guardar.', CURRENT_TIMESTAMP),
                                                 ('No se pudo identificar la pérdida para guardar.', CURRENT_TIMESTAMP),
                                                 ('No se pudo identificar el hallazgo para guardar.', CURRENT_TIMESTAMP),
                                                 ('No se pudo guardar la dirección seleccionada.', CURRENT_TIMESTAMP),
                                                 ('No se pudo guardar la pérdida.', CURRENT_TIMESTAMP),
                                                 ('No se pudo guardar el hallazgo.', CURRENT_TIMESTAMP),
                                                 ('No se pudo vincular la pérdida con sus fotos.', CURRENT_TIMESTAMP),
                                                 ('No se pudo vincular el hallazgo con sus fotos.', CURRENT_TIMESTAMP),
                                                 ('No se pudo registrar la metadata de archivos.', CURRENT_TIMESTAMP),
                                                 ('Debes iniciar sesión para guardar.', CURRENT_TIMESTAMP),
                                                 ('No se pudo obtener el email del usuario logeado.', CURRENT_TIMESTAMP),
                                                 ('No se pudo consultar el usuario.', CURRENT_TIMESTAMP),
                                                 ('No se pudo crear el usuario.', CURRENT_TIMESTAMP),
                                                 ('No se pudo actualizar la pérdida.', CURRENT_TIMESTAMP),
                                                 ('No se pudo crear la pérdida.', CURRENT_TIMESTAMP),
                                                 ('No se encontró la pérdida para asociar fotos.', CURRENT_TIMESTAMP),
                                                 ('No se pudo resolver la dirección.', CURRENT_TIMESTAMP),
                                                 ('No se pudieron consultar direcciones.', CURRENT_TIMESTAMP),
                                                 ('No se pudieron consultar pérdidas.', CURRENT_TIMESTAMP),
                                                 ('No se pudieron consultar hallazgos.', CURRENT_TIMESTAMP),
                                                 ('No se pudieron consultar fotos de pérdidas.', CURRENT_TIMESTAMP),
                                                 ('No se pudieron consultar fotos de hallazgos.', CURRENT_TIMESTAMP),
                                                 ('No se pudieron consultar archivos.', CURRENT_TIMESTAMP),
                                                 ('No se pudieron consultar usuarios.', CURRENT_TIMESTAMP),
                                                 ('Parámetros de límites inválidos.', CURRENT_TIMESTAMP),
                                                 ('Faltan variables de entorno de Supabase.', CURRENT_TIMESTAMP),
                                                 ('La URL de Supabase no es válida.', CURRENT_TIMESTAMP),
                                                 ('No se pudo acceder al bucket "fotos_perdidos".', CURRENT_TIMESTAMP),
                                                 ('No se pudo consultar el usuario.', CURRENT_TIMESTAMP),
                                                 ('No se pudo crear el hallazgo.', CURRENT_TIMESTAMP),
                                                 ('Error inesperado al subir fotos.', CURRENT_TIMESTAMP),
                                                 ('Gracias por registrar la mascota encontrada. Te contactaremos por el correo que utilizaste para identificarte.', CURRENT_TIMESTAMP),
                                                 ('Lamentamos mucho el extravío de su mascota. En caso de que alguien la encuentre, será contactado por el correo que utilizó para identificarse.', CURRENT_TIMESTAMP);