

CREATE TABLE "pet_perdida" (
                               "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                               "date_creacion" timestamp,
                               "nombre_mascota" varchar(30),
                               "date_perdida" timestamp
);

CREATE TABLE "pet_perdida_fotos" (
                                     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                     "id_perdida" bigint NOT NULL,
                                     "id_file" uuid NOT NULL
);

CREATE TABLE "files" (
                         "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
                         "name" varchar(255) NOT NULL,
                         "storage_key" varchar(512) UNIQUE NOT NULL,
                         "bucket_name" varchar(100) NOT NULL,
                         "mime_type" varchar(100) NOT NULL,
                         "size_bytes" bigint NOT NULL,
                         "url" text,
                         "status" varchar(20) DEFAULT 'active',
                         "id_user" uuid,
                         "created_at" timestamp DEFAULT (now()),
                         "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "user" (
                        "id" uuid PRIMARY KEY NOT NULL,
                        "name" varchar
);

COMMENT ON TABLE "files" IS 'Tabla para registrar metadatos de archivos en el Cloud Bucket';

COMMENT ON COLUMN "files"."name" IS 'Nombre original del archivo';

COMMENT ON COLUMN "files"."storage_key" IS 'Ruta única dentro del bucket (ej: uploads/user_1/profile.png)';

COMMENT ON COLUMN "files"."bucket_name" IS 'Nombre del bucket de origen';

COMMENT ON COLUMN "files"."mime_type" IS 'Tipo de contenido (ej: image/jpeg, application/pdf)';

COMMENT ON COLUMN "files"."size_bytes" IS 'Tamaño en bytes';

COMMENT ON COLUMN "files"."url" IS 'URL pública (opcional, si el bucket no es privado)';

COMMENT ON COLUMN "files"."status" IS 'active, deleted, processing';

COMMENT ON COLUMN "files"."id_user" IS 'Relación con el usuario que subió el archivo (opcional)';

ALTER TABLE "pet_perdida_fotos" ADD CONSTRAINT "perdida_perdida_fotos" FOREIGN KEY ("id_perdida") REFERENCES "pet_perdida" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pet_perdida_fotos" ADD CONSTRAINT "perdida_perdida_files" FOREIGN KEY ("id_file") REFERENCES "files" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "files" ADD CONSTRAINT "user_files" FOREIGN KEY ("id_user") REFERENCES "user" ("id") DEFERRABLE INITIALLY IMMEDIATE;
