CREATE TYPE "estado_encontre" AS ENUM (
  'en_proceso',
  'encontrada',
  'caducada',
  'eliminada'
);

CREATE TABLE "pet_encontre" (
                                "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                "date_creacion" timestamp,
                                "date_encontre" timestamp,
                                "supuesto_nombre" varchar(30),
                                "estado" estado_encontre NOT NULL DEFAULT 'encontrada',
                                "id_address" uuid NOT NULL
);

CREATE TABLE "pet_encontre_fotos" (
                                      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                      "id_encontre" bigint NOT NULL,
                                      "id_file" uuid NOT NULL,
                                      "id_file_miniatura" uuid NOT NULL,
                                      "id_file_nano" uuid NOT NULL
);


ALTER TABLE "pet_encontre_fotos" ADD CONSTRAINT "pet_encontre_fotos_files" FOREIGN KEY ("id_file") REFERENCES "files" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pet_encontre_fotos" ADD CONSTRAINT "pet_encontre_fotos_miniaturas" FOREIGN KEY ("id_file_miniatura") REFERENCES "files" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pet_encontre_fotos" ADD CONSTRAINT "pet_encontre_fotos_nano" FOREIGN KEY ("id_file_nano") REFERENCES "files" ("id") DEFERRABLE INITIALLY IMMEDIATE;
